#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
echo "Starting the storage forecast generation..."

if ! pgrep -x storecast &>/dev/null; then
    echo "Generating a new storage forecast..." | logger -t "storecast-plugin"
    cp -f /usr/local/emhttp/plugins/dwstorecast/misc/storecast.json /tmp/storecast.json
    cp -f /usr/local/emhttp/plugins/dwstorecast/misc/storecast.json /tmp/storecast-dash.json
    nohup storecast --path /mnt/user --json --normalize &>/tmp/storecast.log &
fi
