#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
STORECONF="/boot/config/plugins/dwstorecast/dwstorecast.cfg"
[ -e "$STORECONF" ] && source $STORECONF

echo "Writing the configuration..."

case $FORECASTCRON in
    "disable")
        rm -f /etc/cron.hourly/storecast /etc/cron.daily/storecast /etc/cron.weekly/storecast /etc/cron.monthly/storecast
        ;;
    "hourly")
        cp -f /usr/local/emhttp/plugins/dwstorecast/misc/storecast.cron /etc/cron.hourly/storecast
        chmod 755 /etc/cron.hourly/storecast
        rm -f /etc/cron.daily/storecast /etc/cron.weekly/storecast /etc/cron.monthly/storecast
        ;;
    "daily")
        cp -f /usr/local/emhttp/plugins/dwstorecast/misc/storecast.cron /etc/cron.daily/storecast
        chmod 755 /etc/cron.daily/storecast
        rm -f /etc/cron.hourly/storecast /etc/cron.weekly/storecast /etc/cron.monthly/storecast
        ;;
    "weekly")
        cp -f /usr/local/emhttp/plugins/dwstorecast/misc/storecast.cron /etc/cron.weekly/storecast
        chmod 755 /etc/cron.weekly/storecast
        rm -f /etc/cron.hourly/storecast /etc/cron.daily/storecast /etc/cron.monthly/storecast
        ;;
    "monthly")
        cp -f /usr/local/emhttp/plugins/dwstorecast/misc/storecast.cron /etc/cron.monthly/storecast
        chmod 755 /etc/cron.monthly/storecast
        rm -f /etc/cron.hourly/storecast /etc/cron.daily/storecast /etc/cron.weekly/storecast
        ;;
esac
